import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/footer";
import Floating_footer from "@/components/sections/floating_footer";
import ScrollToTop from "@/components/ScrollToTop";
const inter = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IIC HULT PRIZE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 dark:bg-slate-950`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Footer />
          <Floating_footer />
          <ScrollToTop/>
        </ThemeProvider>
      </body>
    </html>
  );
}
